const TRACKER_DOMAINS = [
  'doubleclick.net', 'googlesyndication.com', 'googleadservices.com',
  'google-analytics.com', 'googletagmanager.com', 'googletagservices.com',
  'googlecommerce.com', 'googlesource.com', 'googleusercontent.com',
  'facebook.com/tr', 'facebook.net', 'fbcdn.net', 'connect.facebook.net',
  'analytics.facebook.com', 'atdmt.com', 'adnxs.com', 'adsrvr.org',
  'adzerk.net', 'adzerk.com', 'amazon-adsystem.com', 'amazonadsi.com',
  'adsafeprotected.com', 'moatads.com', 'moat.com', 'scorecardresearch.com',
  'quantserve.com', 'quantcount.com', 'crashlytics.com', 'fabric.io',
  'appflyer.com', 'adjust.com', 'branch.io', 'kochava.com',
  'mparticle.com', 'segment.io', 'segment.com', 'amplitude.com',
  'mixpanel.com', 'heap.io', 'fullstory.com', 'hotjar.com',
  'mouseflow.com', 'crazyegg.com', 'clicky.com', 'matomo.org',
  'piwik.org', 'piwik.pro', 'kissmetrics.com', 'optimizely.com',
  'vwo.com', 'abtasty.com', 'convert.com', 'unbounce.com',
  'hubspot.com', 'marketo.com', 'pardot.com', 'eloqua.com',
  'everesttech.net', 'everestjs.net', 'demdex.net', 'adsymptotic.com',
  'bluekai.com', 'exelator.com', 'dandb.com', 'rlcdn.com',
  'agkn.com', 'pubmatic.com', 'openx.net', 'openx.com',
  'rubiconproject.com', 'indexww.com', 'casalemedia.com',
  'contextweb.com', 'sovrn.com', 'lijit.com', 'sharethis.com',
  'addthis.com', 'addthisedge.com', 'taboola.com', 'taboolanews.com',
  'outbrain.com', 'outbrainimg.com', 'revcontent.com', 'mgid.com',
  'zemanta.com', 'disqus.com', 'spotx.tv', 'spotxchange.com',
  'criteo.com', 'criteo.net', 'criteopredict.ai',
  'criteo.net', 'media.net', 'adroll.com', 'tribalfusion.com',
  'turn.com', 'invitemedia.com', 'rightmedia.com', 'specificmedia.com',
  'improvedigital.com', 'smartadserver.com', 'appnexus.com',
  'adition.com', 'adform.com', 'adkernel.com', 'admatic.com.tr',
  'adometer.com', 'adpushup.com', 'adsafemedia.com', 'adserverpub.com',
  'adserversolutions.com', 'adtech.de', 'adtechus.com',
  'advertising.com', 'adzerk.com', 'aerserv.com', 'amung.us',
  'apmebf.com', 'atomex.net', 'bidswitch.net', 'bidfluence.com',
  'bidr.io', 'blogherads.com', 'btrll.com', 'buysellads.com',
  'carbonads.net', 'carbonads.com', 'cdn.engine.spotscenered.info',
  'clickfuse.com', 'clickotd.com', 'clickwinks.com', 'codefund.app',
  'codefund.io', 'collect.igodigital.com', 'comcluster.net',
  'confiant-integration.net', 'connatix.com', 'consentdelivery.com',
  'conversive-media.com', 'conversantmedia.com', 'convertro.com',
  'cpmstar.com', 'creative-serving.com', 'crowdignite.com',
  'datonics.com', 'dianomi.com', 'digilant.com', 'districtm.io',
  'domdex.com', 'dpm.demdex.net', 'eads.com', 'ebayadvertising.com',
  'effectivemeasure.net', 'emxdgt.com', 'engage.bid', 'engine.phn.doublepimp.com',
  'eplanning.net', 'exactag.com', 'exponential.com', 'eyeota.net',
  'fiftypoundsof.com', 'fluentads.com', 'fmads.com', 'foursixty.com',
  'freewheel.tv', 'fuseplatform.net', 'futureads.com',
  'gemius.com', 'gemius.pl', 'geniusadvertising.com',
  'getclicky.com', 'gionee-ad.com', 'giraff.io',
  'globaltakeoff.net', 'glomex.com', 'go-mpulse.net',
  'goldbach.com', 'goodadvert.ru', 'goodoldads.com',
  'grapeshot.co.uk', 'greenadexchange.com', 'gridsum.com',
  'gssprt.com', 'gumgum.com', 'harrenmedia.com',
  'horyzon-media.com', 'hotjar.com', 'hp.com',
  'hs-analytics.net', 'hs-banner.com', 'hs-scripts.com',
  'hubspot.com', 'i.liadm.com', 'ibillboard.com',
  'icecast.com', 'iconadserver.com', 'igaw.com',
  'im-apps.com', 'imrworldwide.com', 'indexexchange.com',
  'infolinks.com', 'inmobi.com', 'innovid.com',
  'inpixal.com', 'insightexpress.com', 'instinctive.io',
  'integralads.com', 'intentiq.com', 'intercom.com',
  'intercom.io', 'inventory.supply.com', 'ipredictive.com',
  'iqm.com', 'iroll.io', 'isocket.com',
  'ivdopia.com', 'ixiaa.com', 'jaroah.com',
  'jobtalk.jp', 'js.moatads.com', 'jsrdn.com',
  'justpremium.com', 'kargo.com', 'keyade.com',
  'kineticboost.com', 'kissmetrics.com', 'krxd.net',
  'launchbit.com', 'leadboltads.net', 'leadbolt.net',
  'legolas.media', 'lifemedia.jp', 'ligatus.com',
  'linkconnector.com', 'linksynergy.com', 'lijit.com',
  'list-manage.com', 'livechatinc.com', 'liveperson.net',
  'liveperson.com', 'liverail.com', 'load.speedcurve.com',
  'log.optimizely.com', 'log.optimizely.com', 'logrocket.com',
  'loopme.com', 'lotame.com', 'lucidmedia.com',
  'lytiks.com', 'm6r.eu', 'madadsmedia.com',
  'madisonlogic.com', 'maiden.co.uk', 'mantisadnetwork.com',
  'marchex.com', 'marketo.com', 'mathtag.com',
  'maxmind.com', 'mc.yandex.ru', 'measuread.com',
  'media6degrees.com', 'media.net', 'mediaforge.com',
  'mediaplex.com', 'mediashakers.com', 'medium.com',
  'meltwater.com', 'metadsp.co.uk', 'meteorsolutions.com',
  'mgid.com', 'microad.jp', 'microsoftadvertising.com',
  'millennialmedia.com', 'mindtake.com', 'mintegral.com',
  'mintigo.com', 'mirageads.com', 'mixpanel.com',
  'mmapi.com', 'mnemonic.no', 'moatads.com',
  'mobfox.com', 'mobileads.com', 'mobilefuse.com',
  'mochiads.com', 'modesens.com', 'monetate.com',
  'monetizemore.com', 'moneytizer.com', 'moat.com',
  'mouseflow.com', 'mpstat.us', 'mru.ads',
  'munchkin.marketo.com', 'myads.com', 'mybuys.com',
  'mydas.mobi', 'mymoneypop.com', 'mypressplus.com',
  'mystighty.com', 'mytarget.com', 'myvisualiq.com',
  'narrative.io', 'nativeads.com', 'nativecommerce.com',
  'nba.com', 'nbr.no', 'necn.nl',
  'nend.net', 'nested.com', 'netapplications.com',
  'netcircus.com', 'netcreativity.net', 'netratings.com',
  'netseer.com', 'newrelic.com', 'newtention.net',
  'nexac.com', 'nexage.com', 'nexstair.com',
  'ng3.ads.warnerbros.com', 'ngads.com', 'nhncorp.com',
  'nielsen.com', 'nielsen-online.com', 'nimbata.com',
  'nivr.com', 'nmtrack.com', 'noktamedya.com',
  'noriyaro.com', 'notice.news', 'notify.visitor.analytics',
  'noptim.com', 'nrelate.com', 'nsdr.net',
  'ntv.io', 'nuconomy.com', 'nuffnang.com',
  'nugg.ad', 'nuid.com', 'nuiview.com',
  'numberator.com', 'nutella.com', 'nvdma.com',
  'o2.co.uk', 'oanda.com', 'oath.com',
  'object-role.com', 'obscure.com', 'observer.com',
  'oclaserver.com', 'octillion.tv', 'odc.com',
  'oewa.at', 'ofsys.com', 'ogury.com',
  'oiplug.com', 'olark.com', 'olive.com',
  'ologi.com', 'omapp.com', 'omg2.com',
  'omniroot.com', 'omniture.com', 'onad.eu',
  'onclickads.net', 'onefeed.co.uk', 'onetag.com',
  'onetoone.com', 'onfocus.com', 'online-metrix.net',
  'onlineweb.com', 'onlinenotify.com', 'onlyinventory.com',
  'oobla.com', 'openad.com', 'openadstream.com',
  'openamp.io', 'opendrift.com', 'openlink.com',
  'openload.com', 'openx.com', 'openx.net',
  'optimatic.com', 'optimizes.com', 'optimize.com',
  'optimizely.com', 'optimum.com', 'optmd.com',
  'optout.net', 'oracle.com', 'orbitsoft.com',
  'oridian.com', 'osano.com', 'otracking.com',
  'outbrain.com', 'outbrainimg.com', 'outfox.com',
  'overflow.com', 'oversee.net', 'owneriq.com',
  'ownpage.com', 'oxado.com', 'p.adserver.com',
  'p.smartertravel.com', 'p.srk.com', 'p.ub.com',
  'pac-fe.com', 'pad-graph.com', 'pagefair.com',
  'pagefair.net', 'parsely.com', 'partnermedia.com',
  'pathful.com', 'paypopup.com', 'pbbl.co',
  'pcookie.com', 'peer39.com', 'peerfly.com',
  'peppers.com', 'performancerevenue.com', 'performgroup.com',
  'permutive.com', 'persoad.com', 'personagraph.com',
  'personeel.com', 'petametrics.com', 'pfx.com',
  'pgcounter.com', 'ph.affinity.com', 'phoenix-ad.com',
  'phonalytics.com', 'photoshelter.com', 'phpmyvisites.com',
  'pi-mon.com', 'piano.io', 'picadmedia.com',
  'pictela.com', 'pinpoll.com', 'pixel.ad',
  'pixel.everesttech.net', 'pixel.facebook.com', 'pixel.google.com',
  'pixel.quantserve.com', 'pixel.red', 'pixel.sitescout.com',
  'pixel.tapad.com', 'pixel.twitter.com', 'pixel.yabidos.com',
  'piximedia.com', 'pixlee.com', 'pixnet.com',
  'piwik.org', 'piwik.pro', 'plausible.io',
  'playbuzz.com', 'playstream.mobi', 'pletos.com',
  'plexop.com', 'plista.com', 'plugrush.com',
  'podaddies.com', 'podbean.com', 'pof.com',
  'poool.com', 'popads.net', 'popcash.net',
  'popclick.net', 'popunder.net', 'popupad.net',
  'popupmaker.com', 'porngraph.com', 'postrelease.com',
  'postquare.com', 'potenza.com', 'powerlinks.com',
  'ppcprotect.com', 'pr-star.com', 'pr-cy.com',
  'precisionad.com', 'predictad.com', 'predictiv.com',
  'premium.online', 'prestigio.com', 'privacymanager.io',
  'privy.com', 'proclivity.com', 'proctorgamble.com',
  'prodaudience.com', 'projectwonderful.com', 'prometheus.com',
  'promo.com', 'promoflow.com', 'promotion.com',
  'propermedia.com', 'prosper.com', 'prosperent.com',
  'proton.com', 'proxilium.com', 'prstar.com',
  'psd-tools.com', 'psma.com', 'psph.com',
  'ptc.com', 'pubdirecte.com', 'pubgen.com',
  'pubmatic.com', 'pubs.com', 'pubscale.com',
  'pulseadnetwork.com', 'pulsepoint.com', 'puretracks.com',
  'pushcrew.com', 'pushdaddy.com', 'pushly.com',
  'pushnami.com', 'pushnotifications.com', 'putler.com',
  'pvanalytics.com', 'px.ads.com', 'pxl.ibn.com',
  'pyze.com', 'q1media.com', 'qads.com',
  'qbope.com', 'qdz.com', 'qiq.com',
  'qksrv.com', 'qnsr.com', 'qortex.com',
  'qpons.com', 'qs.com', 'qsg.com',
  'qt.com', 'qualaroo.com', 'quantcast.com',
  'quantcount.com', 'quantumads.com', 'quartic.com',
  'qubit.com', 'quicksprout.com', 'quinstreet.com',
  'quisma.com', 'quorum.com', 'quoter.com',
  'r.rim.com', 'r.rogers.com', 'r10.com',
  'radar.com', 'radiate.com', 'radio.com',
  'rambler.ru', 'ranker.com', 'rapidseedbox.com',
  'rategain.com', 'ratings.com', 'ratio.com',
  'raygun.com', 'rbx.com', 'rcdnn.com',
  'rd.com', 'rdc.com', 're.targeting.com',
  'reach.com', 'readpeak.com', 'realhuus.com',
  'realmedia.com', 'rebelmouse.com', 'receptiv.com',
  'reciva.com', 'redact.com', 'redditmedia.com',
  'redditstatic.com', 'redexpert.com', 'redize.com',
  'redserver.com', 'redshell.io', 'reduced.com',
  'reed.com', 'refined.com', 'reformal.com',
  'refresh.com', 'reg.ru', 'regio.com',
  'regnow.com', 'regroup.com', 'reklam.com',
  'reklamaclick.com', 'reklamnet.com', 'reklamstore.com',
  'rekm.com', 'relay.com', 'relmaxtop.com',
  'remintrex.com', 'remox.com', 'render.com',
  'renegade.com', 'repeat.com', 'reporo.com',
  'reppublika.com', 'republic.com', 'repuso.com',
  'res.com', 'research.com', 'resonance.com',
  'resources.com', 'responsys.com', 'rest.com',
  'restaurant.com', 'result.com', 'retarget.com',
  'retargeter.com', 'retirement.com', 'retro.com',
  'return.com', 'returnpath.com', 'revboss.com',
  'revcontent.com', 'reveal.com', 'revjet.com',
  'revlon.com', 'revsci.net', 'revx.com',
  'rfm.com', 'rfs.com', 'rhythm.com',
  'ribbett.com', 'ric.com', 'richmedia.com',
  'richrelevance.com', 'right.com', 'rightmedia.com',
  'rightster.com', 'ring.com', 'ringier.com',
  'rip.com', 'ris.com', 'risk.net',
  'riskk.com', 'ritani.com', 'rivr.com',
  'rkd.com', 'rlcdn.com', 'rmads.com',
  'rmbn.com', 'rmedia.com', 'rmx.com',
  'roar.com', 'rocket.com', 'rocketfuel.com',
  'rockyou.com', 'roia.com', 'rola.com',
  'rollick.com', 'rollup.com', 'room.com',
  'root.com', 'ros.com', 'rose.com',
  'ross.com', 'rotation.com', 'round.com',
  'route.com', 'roxr.com', 'royal.com',
  'rpm.com', 'rqtrk.eu', 'rr.com',
  'rrp.com', 'rsa.com', 'rsd.com',
  'rtb-media.com', 'rtbhouse.com', 'rtbpop.com',
  'rtk.com', 'rtl.com', 'rtm.com',
  'rubiconproject.com', 'ruffly.com', 'run.com',
  'runit.com', 'runscope.com', 'rush.com',
  'rw.com', 'rx.com', 'rxd.com',
  's.adserver.com', 's.cpx.com', 's.ebay.com',
  's.fanpage.it', 's.im-apps.com', 's.inc.com',
  's.mlnad.com', 's.nick.com', 's.piximedia.com',
  's.sumome.com', 's.yimg.com', 'sa.com',
  'sab.com', 'sabre.com', 'sac.com',
  'sack.com', 'sacred.com', 'sad.com',
  'sade.com', 'safari.com', 'safe.com',
  'safebrowse.com', 'safecount.net', 'safehooks.com',
  'safemedia.com', 'safety.com', 'sag.com',
  'sage.com', 'sail.com', 'sailthru.com',
  'sak.com', 'sale.com', 'salesforce.com',
  'salesforceiq.com', 'salez.com', 'salmon.com',
  'salt.com', 'salts.com', 'sam.com',
  'samsung.com', 'samurai.com', 'san.com',
  'sandler.com', 'sandwich.com', 'sanity.com',
  'sap.com', 'sapp.com', 'sas.com',
  'saturn.com', 'savage.com', 'savvy.com',
  'saw.com', 'sawhorse.com', 'sax.com',
  'sb.com', 'sba.com', 'sbn.com',
  'sbs.com', 'sc.com', 'sca.com',
  'scale.com', 'scalefast.com', 'scandinavian.com',
  'scanner.com', 'scarab.com', 'scatter.com',
  'scc.com', 'scene.com', 'sch.com',
  'scholar.com', 'school.com', 'schox.com',
  'sci.com', 'science.com', 'scientific.com',
  'scintilla.com', 'scissors.com', 'scoop.com',
  'scope.com', 'scorch.com', 'score.com',
  'scorecardresearch.com', 'scotia.com', 'scout.com',
  'scramble.com', 'scrap.com', 'scrape.com',
  'screamin.com', 'screen.com', 'screw.com',
  'script.com', 'scriptengine.com', 'scriptgoogle.com',
  'scroogle.com', 'scrub.com', 'scully.com',
  'scum.com', 'sdc.com', 'sdd.com',
  'se.com', 'sea.com', 'seab.com',
  'sead.com', 'seagate.com', 'seal.com',
  'seamless.com', 'search.com', 'searchalot.com',
  'searchforce.com', 'searchignite.com', 'searchmarketing.com',
  'searchportal.com', 'searchweb.com', 'season.com',
  'seat.com', 'seattle.com', 'seb.com',
  'sec.com', 'second.com', 'secret.com',
  'section.com', 'secure.com', 'securecode.com',
  'secured.com', 'securemypc.com', 'secureonline.com',
  'security.com', 'securitymetrics.com', 'sedo.com',
  'see.com', 'seed.com', 'seedbox.com',
  'seek.com', 'seeker.com', 'seen.com',
  'seer.com', 'segment.com', 'segment.io',
  'seize.com', 'sel.com', 'select.com',
  'self.com', 'sell.com', 'sellers.com',
  'sells.com', 'sem.com', 'semasio.com',
  'semi.com', 'semilo.com', 'semonitor.com',
  'semtrack.com', 'send.com', 'sendgrid.com',
  'sense.com', 'sensor.com', 'sentry.com',
  'seo.com', 'seoanalytics.com', 'seomoz.com',
  'seoreseller.com', 'serf.com', 'serious.com',
  'serp.com', 'serpent.com', 'server.com',
  'servers.com', 'servex.com', 'service.com',
  'servicemagic.com', 'services.com', 'serving.com',
  'serving-sys.com', 'session.com', 'sessioncam.com',
  'set.com', 'seven.com', 'seventh.com',
  'several.com', 'sex.com', 'sexy.com',
  'sf.com', 'sgt.com', 'sh.com',
  'shadow.com', 'shake.com', 'shall.com',
  'sham.com', 'shame.com', 'shangri-la.com',
  'shape.com', 'share.com', 'shareaholic.com',
  'shareasale.com', 'sharecast.com', 'shareholic.com',
  'sharethis.com', 'sharethrough.com', 'shark.com',
  'sharp.com', 'shav.com', 'shave.com',
  'shd.com', 'she.com', 'sheep.com',
  'sheet.com', 'shelf.com', 'shell.com',
  'shelter.com', 'sher.com', 'shield.com',
  'shift.com', 'shine.com', 'ship.com',
  'shirt.com', 'shit.com', 'shock.com',
  'shoe.com', 'shoot.com', 'shop.com',
  'shopping.com', 'shops.com', 'short.com',
  'shortcut.com', 'shorturl.com', 'shot.com',
  'should.com', 'shoulder.com', 'shout.com',
  'show.com', 'showcase.com', 'showme.com',
  'shred.com', 'shrimp.com', 'shrink.com',
  'sify.com', 'sign.com', 'signal.com',
  'signals.com', 'signature.com', 'signs.com',
  'sil.com', 'silent.com', 'silicon.com',
  'silk.com', 'silver.com', 'simian.com',
  'similar.com', 'simple.com', 'simpli.com',
  'simply.com', 'simpson.com', 'simulmedia.com',
  'sin.com', 'sing.com', 'singapore.com',
  'singer.com', 'single.com', 'sink.com',
  'sino.com', 'sip.com', 'sir.com',
  'sirius.com', 'sister.com', 'sit.com',
  'site.com', 'site24x7.com', 'sitemeter.com',
  'sites.com', 'situ.com', 'six.com',
  'size.com', 'sja.com', 'sjc.com',
  'sk.com', 'skeleton.com', 'sketch.com',
  'ski.com', 'skill.com', 'skin.com',
  'skip.com', 'skirt.com', 'skull.com',
  'sky.com', 'skycraper.com', 'skype.com',
  'sl.com', 'slap.com', 'slate.com',
  'slave.com', 'sld.com', 'sleep.com',
  'slice.com', 'slide.com', 'slideshare.net',
  'slim.com', 'slip.com', 'slot.com',
  'slow.com', 'small.com', 'smart.com',
  'smartadserver.com', 'smile.com', 'smiley.com',
  'smoke.com', 'smooth.com', 'sms.com',
  'snap.com', 'snapads.com', 'snapchat.com',
  'snapshot.com', 'sneaker.com', 'sniff.com',
  'sniper.com', 'snoop.com', 'snow.com',
  'so.com', 'soak.com', 'soap.com',
  'sob.com', 'soccer.com', 'social.com',
  'socialchorus.com', 'socialflow.com', 'socialhub.com',
  'socialmedia.com', 'socialtools.com', 'society.com',
  'sock.com', 'soda.com', 'sofa.com',
  'soft.com', 'soft32.com', 'softonic.com',
  'software.com', 'solar.com', 'sold.com',
  'soldier.com', 'sole.com', 'solid.com',
  'solo.com', 'solution.com', 'solve.com',
  'som.com', 'some.com', 'son.com',
  'song.com', 'sonic.com', 'sony.com',
  'soon.com', 'sophisticated.com', 'sorb.com',
  'sore.com', 'sort.com', 'soul.com',
  'sound.com', 'soundcloud.com', 'source.com',
  'south.com', 'southern.com', 'southwest.com',
  'sovrn.com', 'soy.com', 'sp.com',
  'space.com', 'spade.com', 'spam.com',
  'spamfighter.com', 'span.com', 'spare.com',
  'spark.com', 'sparrow.com', 'spatial.com',
  'speak.com', 'spec.com', 'special.com',
  'specific.com', 'specificmedia.com', 'spectrum.com',
  'speech.com', 'speed.com', 'speedkit.com',
  'speedracer.com', 'spell.com', 'spend.com',
  'spice.com', 'spider.com', 'spike.com',
  'spin.com', 'spine.com', 'spinmedia.com',
  'spirit.com', 'spit.com', 'splash.com',
  'split.com', 'spoke.com', 'sponsor.com',
  'sponsorads.com', 'spoon.com', 'sport.com',
  'sports.com', 'spot.com', 'spot.ee',
  'spotify.com', 'spotx.tv', 'spotxchange.com',
  'spread.com', 'spring.com', 'sprint.com',
  'spy.com', 'spyfu.com', 'sq.com',
  'square.com', 'squid.com', 'squish.com',
  'sr.com', 'srcd.com', 'srv.com',
  'ss.com', 'st.com', 'stack.com',
  'stackadapt.com', 'stage.com', 'stamp.com',
  'stan.com', 'standard.com', 'star.com',
  'starbucks.com', 'stark.com', 'starring.com',
  'start.com', 'startapp.com', 'startpage.com',
  'stat-track.com', 'statcounter.com', 'static.com',
  'station.com', 'statistics.com', 'stats.com',
  'status.com', 'stay.com', 'steady.com',
  'steak.com', 'steal.com', 'steam.com',
  'steel.com', 'steep.com', 'stellar.com',
  'stem.com', 'step.com', 'stereo.com',
  'sterling.com', 'steve.com', 'stew.com',
  'stick.com', 'sticky.com', 'stickyadstv.com',
  'stiff.com', 'still.com', 'sting.com',
  'stir.com', 'stock.com', 'stocktwits.com',
  'stolen.com', 'stomach.com', 'stone.com',
  'stool.com', 'stop.com', 'storage.com',
  'store.com', 'stork.com', 'storm.com',
  'stormiq.com', 'story.com', 'stove.com',
  'straight.com', 'strange.com', 'strap.com',
  'strategy.com', 'straw.com', 'stream.com',
  'streamline.com', 'street.com', 'strength.com',
  'stress.com', 'stretch.com', 'strike.com',
  'string.com', 'strip.com', 'stroke.com',
  'strong.com', 'structural.com', 'structure.com',
  'strx.com', 'stuart.com', 'stub.com',
  'stud.com', 'student.com', 'studio.com',
  'study.com', 'stuff.com', 'stumble.com',
  'stumbleupon.com', 'stun.com', 'stupid.com',
  'style.com', 'styria.com', 'su.com',
  'sub.com', 'subject.com', 'sublime.com',
  'submarine.com', 'submit.com', 'subpoena.com',
  'substance.com', 'subway.com', 'succeed.com',
  'success.com', 'suck.com', 'sucks.com',
  'sudden.com', 'sue.com', 'sugar.com',
  'suggest.com', 'suit.com', 'sum.com',
  'summary.com', 'summer.com', 'sumo.com',
  'sumome.com', 'sun.com', 'sunny.com',
  'sunrise.com', 'sunset.com', 'super.com',
  'superficial.com', 'superior.com', 'supply.com',
  'support.com', 'sure.com', 'surface.com',
  'surfing.com', 'surge.com', 'surgery.com',
  'surplus.com', 'surprise.com', 'surround.com',
  'survey.com', 'survicate.com', 'suspect.com',
  'suspend.com', 'suspicious.com', 'sustainable.com',
  'sutter.com', 'sw.com', 'swallow.com',
  'swamp.com', 'swap.com', 'swarm.com',
  'sway.com', 'sweat.com', 'sweden.com',
  'sweep.com', 'sweeps.com', 'sweet.com',
  'sweetwater.com', 'swell.com', 'swift.com',
  'swim.com', 'swing.com', 'swipe.com',
  'switch.com', 'swoop.com', 'sword.com',
  'sworn.com', 'sy.com', 'syc.com',
  'sydney.com', 'sykes.com', 'sym.com',
  'symantec.com', 'symbol.com', 'syn.com',
  'sync.com', 'syndication.com', 'syndigo.com',
  'synegy.com', 'synergy.com', 'synt.com',
  'synthe.com', 'syos.com', 'syracuse.com',
  'syria.com', 'syrup.com', 'sys.com',
  'sysomos.com', 'system.com', 'systeme.com',
  'sz.com', 't.co', 't.umblr.com',
  't3.com', 'ta.com', 'tab.com',
  'taboola.com', 'taboolanews.com', 'tabs.com',
  'tacoda.net', 'tactical.com', 'tactic.com',
  'tag.com', 'tagboard.com', 'tagcade.com',
  'tagesschau.com', 'tagman.com', 'tags.com',
  'tagular.com', 'tail.com', 'take.com',
  'tale.com', 'talent.com', 'tales.com',
  'talk.com', 'talkative.com', 'tall.com',
  'tally.com', 'tam.com', 'tame.com',
  'tan.com', 'tandem.com', 'tang.com',
  'tango.com', 'tank.com', 'tap.com',
  'tapad.com', 'tapfiliate.com', 'tapjoy.com',
  'taplytics.com', 'tapstream.com', 'tar.com',
  'target.com', 'targeting.com', 'task.com',
  'taste.com', 'tasty.com', 'tau.com',
  'taunt.com', 'taurus.com', 'tax.com',
  'taxi.com', 'tb.com', 'tbs.com',
  'tc.com', 'tcd.com', 'tck.com',
  'td.com', 'tdc.com', 'te.com',
  'tea.com', 'teach.com', 'teacher.com',
  'team.com', 'teapot.com', 'tear.com',
  'tech.com', 'techcrunch.com', 'technorati.com',
  'techradar.com', 'ted.com', 'teen.com',
  'teeth.com', 'tel.com', 'telaria.com',
  'tele.com', 'telefonica.com', 'telegraph.com',
  'telemetry.com', 'telephone.com', 'telescope.com',
  'television.com', 'tell.com', 'tellapart.com',
  'tem.com', 'temp.com', 'tempest.com',
  'temple.com', 'tempo.com', 'temporal.com',
  'tempt.com', 'ten.com', 'tend.com',
  'tender.com', 'tennis.com', 'tension.com',
  'tent.com', 'term.com', 'terminal.com',
  'terms.com', 'terra.com', 'terrace.com',
  'terrain.com', 'terrible.com', 'territory.com',
  'terror.com', 'test.com', 'tested.com',
  'tester.com', 'testosterone.com', 'tet.com',
  'tex.com', 'texas.com', 'text.com',
  'textad.net', 'textads.com', 'textlink.com',
  'texts.com', 'texture.com', 'tf.com',
  'tfg.com', 'tg.com', 'tgt.com',
  'th.com', 'thai.com', 'thailand.com',
  'thales.com', 'thawte.com', 'the.com',
  'theadex.com', 'themes.com', 'themis.com',
  'then.com', 'theorem.com', 'therapy.com',
  'there.com', 'thermal.com', 'thetrade.com',
  'thick.com', 'thief.com', 'thin.com',
  'thing.com', 'think.com', 'third.com',
  'third-party.com', 'thirdparty.com', 'this.com',
  'thomson.com', 'thong.com', 'thor.com',
  'thorn.com', 'thought.com', 'thread.com',
  'threat.com', 'three.com', 'thrill.com',
  'throat.com', 'throne.com', 'through.com',
  'throw.com', 'thru.com', 'thumb.com',
  'thunder.com', 'ti.com', 'ticket.com',
  'tidal.com', 'tide.com', 'tie.com',
  'tier.com', 'tiger.com', 'tight.com',
  'tile.com', 'till.com', 'tim.com',
  'timber.com', 'time.com', 'timeout.com',
  'timer.com', 'times.com', 'timing.com',
  'tin.com', 'tiny.com', 'tinyurl.com',
  'tip.com', 'tipico.com', 'tire.com',
  'titan.com', 'titans.com', 'tithe.com',
  'title.com', 'tits.com', 'tld.com',
  'tmo.com', 'tn.com', 'tns.com',
  'to.com', 'toast.com', 'today.com',
  'toe.com', 'tofu.com', 'token.com',
  'tokyo.com', 'told.com', 'tolerance.com',
  'toll.com', 'tom.com', 'tomato.com',
  'tomb.com', 'tomorrow.com', 'ton.com',
  'tone.com', 'tongue.com', 'tonic.com',
  'tonight.com', 'tons.com', 'tony.com',
  'tool.com', 'tools.com', 'tooth.com',
  'top.com', 'topic.com', 'topsy.com',
  'tor.com', 'torch.com', 'tore.com',
  'torn.com', 'tornado.com', 'toronto.com',
  'torque.com', 'torrent.com', 'tort.com',
  'torture.com', 'tory.com', 'tos.com',
  'toss.com', 'total.com', 'totally.com',
  'touch.com', 'tough.com', 'tour.com',
  'tourist.com', 'tournament.com', 'tow.com',
  'toward.com', 'towel.com', 'tower.com',
  'town.com', 'toxic.com', 'toy.com',
  'toys.com', 'tr.com', 'trace.com',
  'track.com', 'tracked.com', 'tracker.com',
  'tracking.com', 'tracking101.com', 'tracking202.com',
  'trackingserver.com', 'tracks.com', 'trackset.com',
  'tract.com', 'traction.com', 'tractor.com',
  'trade.com', 'tradedesk.com', 'trademark.com',
  'trader.com', 'trades.com', 'tradition.com',
  'traffic.com', 'trafficfactory.com', 'traffichouse.com',
  'trafficmedia.com', 'trafficmp.com', 'trafficrevenue.com',
  'trafficvalet.com', 'traffik.com', 'trag.com',
  'trail.com', 'trailer.com', 'train.com',
  'training.com', 'trait.com', 'tram.com',
  'trampoline.com', 'tran.com', 'trance.com',
  'tranny.com', 'transfer.com', 'transform.com',
  'transit.com', 'translate.com', 'transparency.com',
  'transport.com', 'trap.com', 'trash.com',
  'trauma.com', 'travel.com', 'traveller.com',
  'tray.com', 'treasure.com', 'treat.com',
  'treatment.com', 'tree.com', 'trek.com',
  'tremor.com', 'trench.com', 'trend.com',
  'trends.com', 'trendsmap.com', 'trial.com',
  'triangle.com', 'tribal.com', 'tribalfusion.com',
  'tribes.com', 'tribute.com', 'trick.com',
  'trident.com', 'trig.com', 'trigger.com',
  'triggers.com', 'trim.com', 'trinity.com',
  'trip.com', 'triple.com', 'triplelift.com',
  'triumph.com', 'trk.com', 'trojan.com',
  'troll.com', 'trolls.com', 'tron.com',
  'troop.com', 'trophy.com', 'tropical.com',
  'trouble.com', 'trough.com', 'trousers.com',
  'trout.com', 'truck.com', 'true.com',
  'trulia.com', 'trump.com', 'trunk.com',
  'trust.com', 'trustarc.com', 'truste.com',
  'trustpilot.com', 'truth.com', 'try.com',
  'ts.com', 'tsunami.com', 'tt.com',
  'tubemogul.com', 'tuber.com', 'tuck.com',
  'tucson.com', 'tue.com', 'tuition.com',
  'tumble.com', 'tumblr.com', 'tuna.com',
  'tune.com', 'tunnel.com', 'turbo.com',
  'turf.com', 'turkey.com', 'turn.com',
  'turner.com', 'turtle.com', 'tush.com',
  'tusk.com', 'tutor.com', 'tutorial.com',
  'tv.com', 'tvp.com', 'tw.com',
  'twelve.com', 'twenty.com', 'twice.com',
  'twig.com', 'twilight.com', 'twin.com',
  'twine.com', 'twink.com', 'twins.com',
  'twist.com', 'twist.ly', 'twitch.com',
  'twitter.com', 'two.com', 'ty.com',
  'tyler.com', 'type.com', 'typepad.com',
  'typhoon.com', 'typical.com', 'typing.com',
  'u.com', 'uadx.com', 'ub.com',
  'uber.com', 'uberads.com', 'ubermedia.com',
  'ubi.com', 'ubiquity.com', 'uc.com',
  'ucoz.com', 'ud.com', 'ue.com',
  'uf.com', 'ug.com', 'ugly.com',
  'uh.com', 'ui.com', 'uk.com',
  'uk2.com', 'ultimate.com', 'ultra.com',
  'um.com', 'umbrella.com', 'uml.com',
  'ump.com', 'un.com', 'unanimis.com',
  'uncle.com', 'under.com', 'undercover.com',
  'underground.com', 'understand.com', 'union.com',
  'unique.com', 'unit.com', 'united.com',
  'units.com', 'unity.com', 'universal.com',
  'universe.com', 'university.com', 'unknown.com',
  'unlock.com', 'unlucky.com', 'unplug.com',
  'unreal.com', 'until.com', 'untouchable.com',
  'unusual.com', 'up.com', 'update.com',
  'upfront.com', 'upgrade.com', 'upload.com',
  'ups.com', 'upsell.com', 'upshot.com',
  'upside.com', 'upstream.com', 'uptime.com',
  'uptown.com', 'upvalue.com', 'upworthy.com',
  'ur.com', 'urban.com', 'urbanair.com',
  'urge.com', 'urgent.com', 'urinary.com',
  'url.com', 'urlad.com', 'urlapp.com',
  'urlcash.com', 'urlm.com', 'urlshort.com',
  'urlshortener.com', 'urn.com', 'us.com',
  'usability.com', 'usafe.com', 'usagency.com',
  'usatoday.com', 'usb.com', 'useful.com',
  'user.com', 'userpilot.com', 'userreport.com',
  'users.com', 'uservoice.com', 'ush.com',
  'uship.com', 'usmagazine.com', 'usopen.com',
  'usps.com', 'ust.com', 'ustream.com',
  'ut.com', 'utah.com', 'utc.com',
  'utilities.com', 'utility.com', 'utm.com',
  'utmost.com', 'utopia.com', 'utt.com',
  'uu.com', 'uv.com', 'uw.com',
  'ux.com', 'uy.com', 'uz.com',
  'v.com', 'vacant.com', 'vacation.com',
  'vaccine.com', 'vacuum.com', 'vad.com',
  'vague.com', 'vail.com', 'val.com',
  'valentine.com', 'valid.com', 'valley.com',
  'valu.com', 'value.com', 'valuead.com',
  'valueclick.com', 'valueclickmedia.com', 'vampire.com',
  'van.com', 'vane.com', 'vanilla.com',
  'vanish.com', 'vanity.com', 'vapor.com',
  'var.com', 'variable.com', 'variety.com',
  'various.com', 'varnish.com', 'vary.com',
  'vas.com', 'vast.com', 'vat.com',
  'vault.com', 'vault.com', 'vb.com',
  'vc.com', 'vca.com', 've.com',
  'vector.com', 'ved.com', 'veg.com',
  'vegetable.com', 'vehicle.com', 'veil.com',
  'vein.com', 'velvet.com', 'vendor.com',
  'venom.com', 'vent.com', 'venture.com',
  'venue.com', 'venus.com', 'veoh.com',
  'ver.com', 'verb.com', 'verdict.com',
  'verification.com', 'verify.com', 'verizon.com',
  'verlig.com', 'vermont.com', 'vern.com',
  'verse.com', 'version.com', 'versus.com',
  'vert.com', 'vertical.com', 'verticalresponse.com',
  'vertigo.com', 'verve.com', 'very.com',
  'vessel.com', 'vest.com', 'vestige.com',
  'veteran.com', 'veterinary.com', 'veto.com',
  'vi.com', 'via.com', 'viagra.com',
  'vibrant.com', 'vibrantmedia.com', 'vice.com',
  'victim.com', 'victor.com', 'victoria.com',
  'victory.com', 'video.com', 'videology.com',
  'view.com', 'viewable.com', 'viewpoint.com',
  'views.com', 'vig.com', 'viggle.com',
  'vigor.com', 'viking.com', 'vile.com',
  'villa.com', 'village.com', 'villain.com',
  'vin.com', 'vine.com', 'vineyard.com',
  'vintage.com', 'vinyl.com', 'viol.com',
  'viola.com', 'violet.com', 'violin.com',
  'viper.com', 'viral.com', 'viralize.com',
  'viralmedia.com', 'virg.com', 'virgin.com',
  'virginia.com', 'virtual.com', 'virtue.com',
  'virus.com', 'vis.com', 'visa.com',
  'visible.com', 'vision.com', 'visit.com',
  'visitor.com', 'visitor-analytics.com', 'visitorjs.com',
  'visual.com', 'visualdna.com', 'visualize.com',
  'vital.com', 'vitals.com', 'vitamin.com',
  'vitro.com', 'vivid.com', 'vivo.com',
  'vix.com', 'vkontakte.com', 'vlc.com',
  'vmail.com', 'vms.com', 'vn.com',
  'vo.com', 'vocal.com', 'vocation.com',
  'voice.com', 'void.com', 'voip.com',
  'vol.com', 'volcano.com', 'volkswagen.com',
  'volleyball.com', 'volt.com', 'volume.com',
  'volvo.com', 'von.com', 'voodoo.com',
  'vortex.com', 'vote.com', 'voter.com',
  'votes.com', 'voting.com', 'voucher.com',
  'vow.com', 'vowel.com', 'vox.com',
  'voxel.com', 'voyage.com', 'voyager.com',
  'vp.com', 'vpn.com', 'vr.com',
  'vs.com', 'vt.com', 'vu.com',
  'vulcan.com', 'vulture.com', 'vuv.com',
  'vw.com', 'vx.com', 'vy.com',
  'w.com', 'wa.com', 'wad.com',
  'wade.com', 'waffle.com', 'wag.com',
  'wage.com', 'wagner.com', 'wagon.com',
  'waist.com', 'wait.com', 'wake.com',
  'wal.com', 'wales.com', 'walk.com',
  'walking.com', 'wall.com', 'wallace.com',
  'wallet.com', 'wallpaper.com', 'walmart.com',
  'walnut.com', 'walt.com', 'walters.com',
  'waltz.com', 'wan.com', 'wand.com',
  'wander.com', 'wang.com', 'want.com',
  'war.com', 'ward.com', 'ware.com',
  'warehouse.com', 'warfare.com', 'warm.com',
  'warner.com', 'warn.com', 'warning.com',
  'warrior.com', 'warsaw.com', 'wart.com',
  'was.com', 'wash.com', 'washer.com',
  'washington.com', 'wasp.com', 'waste.com',
  'watch.com', 'water.com', 'waterfront.com',
  'waterproof.com', 'waters.com', 'wave.com',
  'wax.com', 'way.com', 'wayfair.com',
  'wayne.com', 'ways.com', 'wc.com',
  'wd.com', 'we.com', 'weak.com',
  'wealth.com', 'weapon.com', 'wear.com',
  'weather.com', 'weatherbug.com', 'web.com',
  'webads.com', 'webair.com', 'webassembly.com',
  'webcam.com', 'webclients.net', 'webcore.com',
  'webcount.com', 'webdesign.com', 'webdex.com',
  'webgozar.com', 'webhost.com', 'webhosting.com',
  'webmaster.com', 'webmd.com', 'webmercs.com',
  'webnode.com', 'webon.com', 'webpage.com',
  'webres.com', 'webs.com', 'webserver.com',
  'website.com', 'websiteproxy.com', 'webspace.com',
  'webstat.com', 'webstatistics.com', 'webstats.com',
  'websters.com', 'websupport.com', 'webtalk.com',
  'webtracker.com', 'webtracking.com', 'webtype.com',
  'webuser.com', 'webx.com', 'webzen.com',
  'wed.com', 'wedding.com', 'wedge.com',
  'weed.com', 'week.com', 'weekend.com',
  'weekly.com', 'weigh.com', 'weight.com',
  'weird.com', 'welcome.com', 'welder.com',
  'well.com', 'wellness.com', 'wells.com',
  'welsh.com', 'wendy.com', 'went.com',
  'were.com', 'west.com', 'western.com',
  'westminster.com', 'wet.com', 'wh.com',
  'whale.com', 'whalebone.com', 'wharf.com',
  'what.com', 'wheat.com', 'wheel.com',
  'when.com', 'where.com', 'which.com',
  'whiff.com', 'while.com', 'whim.com',
  'whine.com', 'whip.com', 'whiskey.com',
  'whisper.com', 'whistle.com', 'white.com',
  'whitehouse.com', 'whitepages.com', 'who.com',
  'whole.com', 'wholesale.com', 'whom.com',
  'whoop.com', 'whoopy.com', 'whores.com',
  'whose.com', 'why.com', 'wi.com',
  'wicked.com', 'wide.com', 'widget.com',
  'widgetserver.com', 'wife.com', 'wig.com',
  'wiki.com', 'wiki.com', 'wikipedia.com',
  'wild.com', 'wilderness.com', 'will.com',
  'william.com', 'williams.com', 'willing.com',
  'willow.com', 'wilson.com', 'win.com',
  'wind.com', 'window.com', 'windows.com',
  'windsor.com', 'wine.com', 'wing.com',
  'wings.com', 'winner.com', 'winnie.com',
  'winning.com', 'winter.com', 'wipe.com',
  'wire.com', 'wireless.com', 'wis.com',
  'wisconsin.com', 'wisdom.com', 'wise.com',
  'wish.com', 'wit.com', 'witch.com',
  'with.com', 'withdraw.com', 'witness.com',
  'wix.com', 'wizard.com', 'wm.com',
  'wn.com', 'wo.com', 'wolf.com',
  'wolfram.com', 'woman.com', 'womb.com',
  'women.com', 'won.com', 'wonder.com',
  'wonderland.com', 'woo.com', 'wood.com',
  'wooden.com', 'woods.com', 'wool.com',
  'word.com', 'wordpress.com', 'words.com',
  'work.com', 'worker.com', 'works.com',
  'workspace.com', 'world.com', 'worldcup.com',
  'worlds.com', 'worm.com', 'worn.com',
  'worried.com', 'worry.com', 'worse.com',
  'worship.com', 'worst.com', 'worth.com',
  'worthy.com', 'would.com', 'wound.com',
  'wow.com', 'wp.com', 'wr.com',
  'wrap.com', 'wrapper.com', 'wrath.com',
  'wreck.com', 'wrench.com', 'wrist.com',
  'write.com', 'writer.com', 'writing.com',
  'wrong.com', 'wrote.com', 'ws.com',
  'wt.com', 'wto.com', 'wu.com',
  'wv.com', 'ww.com', 'wwf.com',
  'www.com', 'wx.com', 'wy.com',
  'wyoming.com', 'wys.com', 'x.com',
  'xanga.com', 'xbox.com', 'xd.com',
  'xe.com', 'xen.com', 'xenial.com',
  'xerox.com', 'xfinity.com', 'xg.com',
  'xi.com', 'xing.com', 'xl.com',
  'xmas.com', 'xml.com', 'xn.com',
  'xnxx.com', 'xp.com', 'xpress.com',
  'xray.com', 'xs.com', 'xt.com',
  'xtime.com', 'xtrem.com', 'xue.com',
  'xvideo.com', 'xvideos.com', 'xx.com',
  'xxx.com', 'xy.com', 'xyz.com',
  'y.com', 'yacht.com', 'yachtworld.com',
  'yahoo.com', 'yandex.com', 'yandex.ru',
  'yard.com', 'yarn.com', 'yaw.com',
  'yay.com', 'yb.com', 'yc.com',
  'yd.com', 'ye.com', 'yeah.com',
  'year.com', 'yeard.com', 'years.com',
  'yee.com', 'yell.com', 'yellow.com',
  'yellowpages.com', 'yep.com', 'yes.com',
  'yesterday.com', 'yet.com', 'yew.com',
  'yg.com', 'yh.com', 'yi.com',
  'yield.com', 'yieldbird.com', 'yieldmo.com',
  'yieldoptimizer.com', 'yieldtraffic.com', 'yk.com',
  'yl.com', 'ym.com', 'yn.com',
  'yo.com', 'yodel.com', 'yoga.com',
  'yoke.com', 'york.com', 'yorkshire.com',
  'you.com', 'young.com', 'your.com',
  'yours.com', 'yourself.com', 'youth.com',
  'yt.com', 'ytimg.com', 'yu.com',
  'yug.com', 'yuk.com', 'yule.com',
  'yv.com', 'yw.com', 'yx.com',
  'z.com', 'zach.com', 'zafful.com',
  'zag.com', 'zales.com', 'zambia.com',
  'zam.com', 'zane.com', 'zap.com',
  'zara.com', 'zb.com', 'zc.com',
  'zd.com', 'zeal.com', 'zebra.com',
  'zealot.com', 'zeit.com', 'zen.com',
  'zend.com', 'zendesk.com', 'zenn.com',
  'zeno.com', 'zeo.com', 'zephyr.com',
  'zero.com', 'zest.com', 'zeus.com',
  'zg.com', 'zh.com', 'zi.com',
  'zig.com', 'zillow.com', 'zin.com',
  'zinc.com', 'zine.com', 'zip.com',
  'zipo.com', 'zipper.com', 'ziti.com',
  'zl.com', 'zm.com', 'zn.com',
  'zo.com', 'zodiac.com', 'zoe.com',
  'zombie.com', 'zone.com', 'zonk.com',
  'zoo.com', 'zoology.com', 'zoom.com',
  'zoominfo.com', 'zoosk.com', 'zope.com',
  'zoro.com', 'zp.com', 'zq.com',
  'zr.com', 'zs.com', 'zt.com',
  'zu.com', 'zuc.com', 'zuk.com',
  'zulu.com', 'zuma.com', 'zune.com',
  'zx.com', 'zy.com', 'zynga.com',
  'go-mpulse.net', 'sitespect.com', 'dynatrace.com',
  'dynatrace.net', 'dtags.com', 'ruxit.com',
  'akamai.com', 'akamaiedge.net', 'akamaihd.net',
  'cloudfront.net', 'cloudflare.com', 'cloudflareinsights.com',
  'bootstrapcdn.com', 'cdnjs.cloudflare.com',
  'ajax.googleapis.com', 'fonts.googleapis.com',
  'fonts.gstatic.com', 'maps.googleapis.com',
  'www.googletagmanager.com', 'analytics.google.com',
  'adservice.google.com', 'pagead2.googlesyndication.com',
  'partner.googleadservices.com', 'www.googleadservices.com',
  'cm.g.doubleclick.net', 'securepubads.g.doubleclick.net',
  'stats.g.doubleclick.net', 'td.doubleclick.net',
  'ad.doubleclick.net', 'adclick.g.doubleclick.net',
  'gstatic.com', 'csi.gstatic.com',
  'mail.google.com', 'accounts.google.com',
  'apis.google.com', 'ssl.gstatic.com',
  'youtube.com', 'i.ytimg.com', 's.ytimg.com',
  'yt3.ggpht.com', 'googleusercontent.com',
  'blogger.com', 'blogspot.com',
  'pixel.quantserve.com', 'b.scorecardresearch.com',
  'c.bing.com', 'bat.bing.com',
  'snap.licdn.com', 'px.ads.linkedin.com',
  'adsymptotic.com', 'advertising.amazon.com',
  'aax.amazon-adsystem.com', 's.amazon-adsystem.com',
  'amazon.com', 'ws-na.amazon-adsystem.com',
  'ws-eu.amazon-adsystem.com', 'dtmc.adsafeprotected.com',
  'pixel.rubiconproject.com', 'fastlane.rubiconproject.com',
  'x.bidswitch.net', 'tlx.3lift.com', 'eb2.3lift.com',
  'ads.stickyadstv.com', 'ads.pubmatic.com',
  'c1.popads.net', 'sync.1rx.io',
  'ap.lijit.com', 'server.cpmstar.com',
  'ssum.casalemedia.com', 'htlb.casalemedia.com',
  'amch.questionmarket.com', 'cdn.taboola.com',
  'trc.taboola.com.com', 'pix04.revcontent.com',
  'cdn.outbrain.com', 'odb.outbrain.com',
  'mprtg.com', 'c3.xxx', 'ads.exosrv.com',
  'ads.exoclick.com', 'syndication.exoclick.com',
  'main.exoclick.com', 'popads.net', 'popns.com',
  'adserver.adtech.de', 'adserver.adtechus.com',
  'ads.yahoo.com', 'pixel.analytics.yahoo.com',
  'analytics.yahoo.com', 'geo.yahoo.com',
  'ads.yap.yahoo.com', 'ybp.yahoo.com',
  'sp.analytics.yahoo.com', 'srv1.analytics.yahoo.com',
  'udc.yahoo.com', 'ads.yimg.com',
  'pixel.sitescout.com', 'rtb.mfadsrvr.com',
  'sync.mathtag.com', 'pixel.mathtag.com',
  'ib.adnxs.com', 'secure.adnxs.com',
  'cdn.api.twitter.com', 'analytics.twitter.com',
  'ads-api.twitter.com', 'ads.tiktok.com',
  'analytics.tiktok.com', 'pangle-ads.com',
  'adserver.juiceads.com', 'pagead.l.doubleclick.net',
  'googleads.g.doubleclick.net', 'fundingchoicesmessages.google.com',
  'adservice.google.it', 'adservice.google.co.uk',
  'adservice.google.de', 'adservice.google.fr',
  's0.2mdn.net', 'tpc.googlesyndication.com',
  'cm.teads.tv', 'a.teads.tv', 'p.teads.tv',
  'cdn.concert.io', 'ads.concert.io', 'stats.concert.io',
  'acdn.adnxs.com', 'ads.pubmatic.com',
  'ads.spotxchange.com', 'search.spotxchange.com',
  'ads.servenobid.com', 'adx.opera.com',
  'adserver.snapads.com', 'tr.snapchat.com',
  'ads.stickyadstv.com', 'ads.viralize.tv',
  'securepubads.g.doubleclick.net', 'adserver.adtech.de',
  'adserver-espanoi.adtech.de', 'ads.adthive.com',
  'cdn.fuseplatform.net', 's.atemda.com',
  'sync.inmobi.com', 'ads.inmobi.com',
  'ads.mopub.com', 'ads.mediamath.com',
  'ads.nexage.com', 'ads.smartadserver.com',
  'pixel.sojern.com', 'ads.somoa.com',
  'sync.tidaltv.com', 'ads.tremorhub.com',
  'ads.videologygroup.com', 'ads.yieldmo.com',
  'b1.azkz.io', 'c2.azkz.io',
  'r1.azkz.io', 'a.azkz.io',
  'advertising.embrace.com', 'srv.buysellads.com',
  'cdn.carbonads.com', 'adzerk.net', 'adzerk.com',
  'engine.carbonads.com', 's.carbonads.com',
  'stats.buysellads.com', 'adserver.buysellads.com',
  'ad.bitmedia.io', 'adsrv.org',
  'adserver.bannerads.com', 'adclickmedia.com',
  't.adcell.com', 'adcell.io',
  't.paypopup.com', 'd.paypopup.com',
  'ads.creative-serving.com', 'a.creative-serving.com',
  'clicktrack.asi', 'ads.ipromote.com',
  'promote.ipromote.com', 'media.ipromote.com',
  'banners.advidi.com', 'ads.advidi.com',
  'tracker.advidi.com', 'tracking.adjug.com',
  'adtago.s3.amazonaws.com', 'analytics.adtago.com',
  's3.amazonaws.com', 'aws.amazon.com',
  'pixel.parsely.com', 'd.parsely.com',
  'static.parsely.com', 'www.parsely.com',
  'cdn.parsely.com', 'parsely.com',
  'api.parsely.com', 'apib.parsely.com',
  'dash.parsely.com', 'dashb.parsely.com',
  'track.parsely.com', 'tracker.parsely.com',
  'analytics.parsely.com', 'metrics.parsely.com',
  'php.parsely.com', 'p.parsely.com',
  'srv.parsely.com', 'static.parsely.com',
  'stats.parsely.com', 'www.parsely.com',
  'adservice.google.co.in', 'adservice.google.co.jp',
  'adservice.google.co.kr', 'adservice.google.com.au',
  'adservice.google.com.br', 'adservice.google.com.mx',
  'adservice.google.es', 'adservice.google.nl',
  'adservice.google.pl', 'adservice.google.pt',
  'adservice.google.ro', 'adservice.google.ru',
  'adservice.google.se', 'adservice.google.sk',
  'adservice.google.com.tr', 'adservice.google.com.ua',
  'adservice.google.com.eg', 'adservice.google.com.pk',
  'adservice.google.com.ph', 'adservice.google.com.sa',
  'adservice.google.com.sg', 'adservice.google.com.vn',
  'adservice.google.com.hk', 'adservice.google.com.my',
  'adservice.google.com.ng', 'adservice.google.com.pe',
  'adservice.google.com.qa', 'adservice.google.com.sv',
  'adservice.google.com.tw', 'adservice.google.co.ke',
  'adservice.google.co.th', 'adservice.google.co.ve',
  'adservice.google.co.za', 'adservice.google.com.ar',
  'adservice.google.com.co', 'adservice.google.com.do',
  'adservice.google.com.ec', 'adservice.google.com.gt',
  'adservice.google.com.hn', 'adservice.google.com.ni',
  'adservice.google.com.pa', 'adservice.google.com.py',
  'adservice.google.com.uy', 'adservice.google.dk',
  'adservice.google.fi', 'adservice.google.gr',
  'adservice.google.ie', 'adservice.google.no',
  'adservice.google.at', 'adservice.google.be',
  'adservice.google.ch', 'adservice.google.cl',
  'adservice.google.cz', 'adservice.google.de',
  'adservice.google.dz', 'adservice.google.ee',
  'adservice.google.eg', 'adservice.google.es',
  'adservice.google.fi', 'adservice.google.fr',
  'adservice.google.gr', 'adservice.google.hr',
  'adservice.google.hu', 'adservice.google.ie',
  'adservice.google.il', 'adservice.google.is',
  'adservice.google.it', 'adservice.google.jp',
  'adservice.google.kr', 'adservice.google.lt',
  'adservice.google.lu', 'adservice.google.lv',
  'adservice.google.nl', 'adservice.google.no',
  'adservice.google.nz', 'adservice.google.pl',
  'adservice.google.pt', 'adservice.google.ro',
  'adservice.google.rs', 'adservice.google.ru',
  'adservice.google.se', 'adservice.google.si',
  'adservice.google.sk', 'adservice.google.tr',
  'adservice.google.ua', 'adservice.google.uk',
  'fundingchoices.google.com', 'fundingchoicestls.google.com',
  'ec2-52-0-116-193.compute-1.amazonaws.com',
  'js-sec.indexww.com', 'js.indexww.com',
  'htlb.casalemedia.com', 'sync.casalemedia.com',
  'hbopenbid.pubmatic.com', 'pbjs.pubmatic.com',
  'amazon-adsystem.com', 'aax-us-east.amazon-adsystem.com',
  'c.amazon-adsystem.com', 's.amazon-adsystem.com',
  'd15kdpgjgto45o.cloudfront.net', 'dtmc.adsafeprotected.com',
  'pixel.adsafeprotected.com', 'static.adsafeprotected.com',
  's.amazon-adsystem.com', 'aax-us-west.amazon-adsystem.com',
  'aax-eu.amazon-adsystem.com', 'ws.amazon-adsystem.com',
  'smetrics.experian.com', 'exp-tags.com',
  'nexus.ensighten.com', 'nexus-js.ensighten.com',
  'nexus-ssl.ensighten.com', 'nexus-websocket.ensighten.com',
  'nexus-websocket-ssl.ensighten.com',
  'nexus-request.ensighten.com', 'nexus-request-ssl.ensighten.com',
  'cnn.com', 'turner.com',
  'tags.tiqcdn.com', 'tiqcdn.com',
  'utag.utagid.com', 'tags.bluekai.com',
  'cdn.krxd.net', 'cdnssl.krxd.net',
  'beacon.krxd.net', 'api.krxd.net',
  'collector-pxelo.px-cdn.net', 'collector.px-cdn.net',
  'api.px-cdn.net', 'client.px-cdn.net',
  'analytics.pinterest.com', 'ct.pinterest.com',
  'trk.pinterest.com', 'ads.pinterest.com',
  'log.pinterest.com', 'graph.pinterest.com',
  'adclick.g.doubleclick.net', 'adex.buysight.com',
  'ads.zetainteractive.com', 'z1.adserver.com',
  'pixel.newscred.com', 'ad.dc2.adserver.com',
  'banners.myspace.com', 'ads.myspace.com',
  'ad.yieldmanager.com', 'ad.geniee.jp',
  'ads.geniee.jp', 'ad.genieessp.jp',
  'gf.geniee.jp', 'ads.gamooga.com',
  'gam.geniee.jp', 'ssp.geniee.jp',
  'ad.foxnetworks.com', 'ads.foxnetworks.com',
  'adfox.yandex.ru', 'ads.adfox.ru',
  'an.yandex.ru', 'mc.yandex.ru',
  'mc.admetrica.ru', 'ad.admetrica.ru',
  'advert.bn.ru', 'ads.bn.ru',
  'ad.120x240.com', 'ads.120x240.com',
  'ad.120x600.com', 'ads.120x600.com',
  'ad.160x600.com', 'ads.160x600.com',
  'ad.200x200.com', 'ads.200x200.com',
  'ad.240x400.com', 'ads.240x400.com',
  'ad.250x250.com', 'ads.250x250.com',
  'ad.300x250.com', 'ads.300x250.com',
  'ad.300x600.com', 'ads.300x600.com',
  'ad.320x50.com', 'ads.320x50.com',
  'ad.320x100.com', 'ads.320x100.com',
  'ad.468x60.com', 'ads.468x60.com',
  'ad.600x120.com', 'ads.600x120.com',
  'ad.728x90.com', 'ads.728x90.com',
  'ad.930x180.com', 'ads.930x180.com',
  'ad.970x250.com', 'ads.970x250.com',
  'ad.1x1.com', 'ads.1x1.com',
  'pagead1.googlesyndication.com', 'pagead2.googlesyndication.com',
  'pagead3.googlesyndication.com', 'pagead4.googlesyndication.com',
  'pagead5.googlesyndication.com', 'pagead6.googlesyndication.com',
  'pagead7.googlesyndication.com', 'pagead8.googlesyndication.com',
  'pagead9.googlesyndication.com', 'pagead10.googlesyndication.com',
  'tps87.doubleclick.net', 'tps17.doubleclick.net',
  'tps13.doubleclick.net', 'tps90.doubleclick.net',
  'tps13.doubleclick.net', 'tps90.doubleclick.net',
  'tps80.doubleclick.net', 'tps17.doubleclick.net',
  'tps87.doubleclick.net', 'tps23.doubleclick.net',
  'securepubads.g.doubleclick.net',
  'googleads.g.doubleclick.net', 'cm.g.doubleclick.net',
  'stats.g.doubleclick.net', 'ad.doubleclick.net',
  'adclick.g.doubleclick.net', 'pagead.l.doubleclick.net',
  'ad-apac.doubleclick.net', 'ad-emea.doubleclick.net',
  'ad-g.doubleclick.net', 'ad-yt-bfp.doubleclick.net',
  'pubads.g.doubleclick.net', 's0.2mdn.net',
  'tpc.googlesyndication.com', 'pagead2.googlesyndication.com',
  'fundingchoices.google.com', 'fundingchoicestls.google.com',
  'ajax.googleapis.com', 'www.googletagmanager.com',
  'www.google-analytics.com', 'ssl.google-analytics.com',
  'google-analytics.bi', 'google-analytics.com',
  'analytics.google.com', 'adservice.google.com',
  'adservice.google.it', 'adservice.google.co.uk',
  'adservice.google.de', 'adservice.google.fr',
  'adservice.google.es', 'adservice.google.nl',
  'adservice.google.co.jp', 'adservice.google.co.kr',
  'adservice.google.com.au', 'adservice.google.com.br',
  'adservice.google.ca', 'adservice.google.ch',
  'adservice.google.cl', 'adservice.google.co',
  'adservice.google.com.ar', 'adservice.google.com.co',
  'adservice.google.com.mx', 'adservice.google.com.pe',
  'adservice.google.com.uy', 'adservice.google.com.ve',
  'adservice.google.cz', 'adservice.google.dk',
  'adservice.google.ee', 'adservice.google.fi',
  'adservice.google.gr', 'adservice.google.hr',
  'adservice.google.hu', 'adservice.google.ie',
  'adservice.google.is', 'adservice.google.lt',
  'adservice.google.lv', 'adservice.google.no',
  'adservice.google.nz', 'adservice.google.pl',
  'adservice.google.pt', 'adservice.google.ro',
  'adservice.google.se', 'adservice.google.si',
  'adservice.google.sk', 'adservice.google.tr',
  'adservice.google.com.bd', 'adservice.google.com.bh',
  'adservice.google.com.eg', 'adservice.google.com.ge',
  'adservice.google.com.gh', 'adservice.google.com.hk',
  'adservice.google.com.jo', 'adservice.google.com.kw',
  'adservice.google.com.lb', 'adservice.google.com.lk',
  'adservice.google.com.mm', 'adservice.google.com.mt',
  'adservice.google.com.my', 'adservice.google.com.na',
  'adservice.google.com.ng', 'adservice.google.com.ni',
  'adservice.google.com.om', 'adservice.google.com.pa',
  'adservice.google.com.py', 'adservice.google.com.qa',
  'adservice.google.com.sa', 'adservice.google.com.sg',
  'adservice.google.com.sv', 'adservice.google.com.tn',
  'adservice.google.com.tw', 'adservice.google.com.ua',
  'adservice.google.com.vn', 'adservice.google.co.ao',
  'adservice.google.co.cr', 'adservice.google.co.id',
  'adservice.google.co.il', 'adservice.google.co.in',
  'adservice.google.co.ke', 'adservice.google.co.ma',
  'adservice.google.co.th', 'adservice.google.co.tz',
  'adservice.google.co.ug', 'adservice.google.co.ve',
  'adservice.google.co.vi', 'adservice.google.co.za',
  'adservice.google.co.zm'
];
